[build]
  command = "echo 'Static landing for Netlify'"
  publish = "."

[build.environment]
  MISE_DISABLE = "1"
  MISE_PYTHON_COMPILE = "0"

[dev]
  command = "echo 'Netlify static dev'"
  port = 8888
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200