[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-python"

[dev]
  command = "streamlit run app.py"
  port = 8501
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
