[build]
  command = "echo 'Building static landing page'"
  publish = "."

[dev]
  command = "echo 'Static site ready'"
  port = 80
  publish = "."

[[redirects]]
  from = "/*"
  to = "/netlify-static.html"
  status = 200
