[build]
  command = "echo 'Static landing for Netlify'"
  publish = "."

[dev]
  command = "echo 'Netlify static dev'"
  port = 8888
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200